export const portfolioKnowledge = {
  home: {
    keywords: [
      'work',
      'projects',
      'case studies',
      'portfolio',
      'b2p',
      'healthcare',
      'ecommerce',
      'checkout',
      'fintech',
      'showcase',
      'see my work',
      'view projects',
    ],
    title: 'My Work',
    description: 'Explore my latest projects and case studies',
  },
  about: {
    keywords: [
      'about',
      'experience',
      'skills',
      'tools',
      'process',
      'methods',
      'background',
      'who are you',
      'tell me about',
      'biography',
      'career',
      'education',
    ],
    title: 'About Me',
    description: 'Learn about my experience, skills, and design process',
  },
  contact: {
    keywords: [
      'contact',
      'email',
      'reach',
      'work together',
      'get in touch',
      'hire',
      'collaborate',
      'message',
      'connect',
      'inquiry',
    ],
    title: 'Get in Touch',
    description: 'Send me a message or get in touch',
  },
  'case-study-b2p': {
    keywords: ['b2p', 'b2p redesign', 'b2p project', 'procurement', 'business to professional'],
    title: 'B2P Redesign',
    description: 'B2P procurement platform redesign case study',
    caseStudyId: 'b2p-redesign',
  },
  'case-study-healthcare': {
    keywords: ['healthcare', 'health platform', 'patient', 'medical', 'clinic', 'appointment'],
    title: 'Healthcare Platform',
    description: 'Healthcare platform design case study',
    caseStudyId: 'healthcare-platform',
  },
  'case-study-ecommerce': {
    keywords: ['ecommerce', 'e-commerce', 'shopping', 'checkout', 'cart', 'online store'],
    title: 'E-Commerce Checkout',
    description: 'E-Commerce checkout flow optimization case study',
    caseStudyId: 'ecommerce-checkout',
  },
  'case-study-customer-centricity': {
    keywords: ['customer-centricity', 'customer experience', 'cx', 'journey mapping', 'organizational change', 'customer journey', 'strategy', 'leadership', 'team building'],
    title: 'Enabling Customer-Centricity',
    description: 'Customer experience transformation and organizational change case study',
    caseStudyId: 'customer-centricity',
  },
};
