export const portfolioKnowledge = {
  home: {
    keywords: [
      'work',
      'projects',
      'case studies',
      'portfolio',
      'b2p',
      'healthcare',
      'ecommerce',
      'checkout',
      'fintech',
      'showcase',
      'see my work',
      'view projects',
    ],
    title: 'My Work',
    description: 'Explore my latest projects and case studies',
  },
  about: {
    keywords: [
      'about',
      'experience',
      'skills',
      'tools',
      'process',
      'methods',
      'background',
      'who are you',
      'tell me about',
      'biography',
      'career',
      'education',
    ],
    title: 'About Me',
    description: 'Learn about my experience, skills, and design process',
  },
  contact: {
    keywords: [
      'contact',
      'email',
      'reach',
      'work together',
      'get in touch',
      'hire',
      'collaborate',
      'message',
      'connect',
      'inquiry',
    ],
    title: 'Get in Touch',
    description: 'Send me a message or get in touch',
  },
  'case-study-b2p': {
    keywords: ['b2p', 'b2p redesign', 'b2p project', 'procurement', 'business to professional'],
    title: 'B2P Redesign',
    description: 'B2P procurement platform redesign case study',
    caseStudyId: 'b2p-redesign',
  },
  'case-study-healthcare': {
    keywords: ['healthcare', 'health platform', 'patient', 'medical', 'clinic', 'appointment'],
    title: 'Healthcare Platform',
    description: 'Healthcare platform design case study',
    caseStudyId: 'healthcare-platform',
  },
  'case-study-ecommerce': {
    keywords: ['ecommerce', 'e-commerce', 'shopping', 'checkout', 'cart', 'online store'],
    title: 'E-Commerce Checkout',
    description: 'E-Commerce checkout flow optimization case study',
    caseStudyId: 'ecommerce-checkout',
  },
  'case-study-customer-centricity': {
    keywords: ['customer-centricity', 'customer experience', 'cx', 'journey mapping', 'organizational change', 'customer journey', 'strategy', 'leadership', 'team building', 'electricity', 'energy', 'utility', 'organizational transformation', 'customer effort score', 'ces', 'design thinking', 'team scaling', 'stakeholder alignment', 'customer research', 'operations', 'digital transformation', 'solar', 'satisfaction improvement'],
    title: 'Enabling Customer-Centricity',
    description: 'Led organizational transformation at Sweden\'s largest electricity distributor to embed customer-first thinking across operations. Created unified customer journey framework and scaled CX team, achieving 52% customer satisfaction improvement.',
    caseStudyId: 'customer-centricity',
  },
  'case-study-energy-transformation': {
    keywords: ['energy', 'electricity', 'utility', 'customer-centric', 'customer effort score', 'ces', 'organizational transformation', 'customer journey', 'energy company', 'solar', 'renewable'],
    title: 'Customer-Centric Energy Company Transformation',
    description: 'Transforming a utility company into a customer-focused organization with measurable impact',
    caseStudyId: 'customer-energy-transformation',
  },
};
